### ISSUE TITLE
Meteor.loginWithPassword doesn't return while running on phone

### ISSUE THREAD

**Issue by kokokenada** [idanwe/meteor-client-side#11]
I'm running with "ionic serve" and am able to login no problem. When I "ionic run android" and run from my phone, I can't login in. At first I had a hard time figuring out how to make talk to the server. I solved this by adding window.**meteor_runtime_config** = {DDP_DEFAULT_CONNECTION_URL: SERVER_URL};. This made the net::ERR_CONNECTION_TIMED_OUT errors go away, but with I call Meteor.loginWithPassword, it just goes away and doesn't even call me callback with an error.

**Comment by sabativi** [comment]
Could [this](https://github.com/idanwe/meteor-client-side/issues/9) be of any help ?

**Comment by telemakhos** [comment]
@kokokenada Did you manage to solve it whitelisting the domain as explained [here](https://github.com/idanwe/meteor-client-side/issues/9#issuecomment-168488727)?

**Comment by kokokenada** [comment]
Thanks for the reply @Telemakhos . My problem mysteriously went away after using a different approach to loading the libraries.  I can't remember exactly what.  Probably safe to close this issue, so I'm doing so...
