### ISSUE TITLE
this.userId is null on server, populated on client

### ISSUE THREAD

**Issue by kokokenada** [idanwe/meteor-client-side#12]
Meteor.loginWithPassword was successfully called and Meteor.user() looks good.  Collections that don't check this.usedId work fine.  Collections restricted by find({userID: this.userId}) fail because user ID is null on the server. 

```
├─┬ accounts-base-client-side#0.1.1
│ └── meteor-client-side#1.2.1 incompatible with ~0.2.0 (0.2.3 available, latest is 1.2.1)
├─┬ accounts-password-client-side#0.3.1
│ ├─┬ accounts-base-client-side#0.1.1
│ │ └── meteor-client-side#1.2.1
│ └── meteor-client-side#1.2.1 incompatible with ~0.2.3 (0.2.3 available, latest is 1.2.1)
├─┬ angular-material-icons#0.6.0
│ └── angular#1.4.9 (1.5.0-rc.2 available)
├─┬ angular-meteor#1.3.5
│ ├── angular#1.4.9 incompatible with 1.4.4 (1.4.4 available, latest is 1.5.0-rc.2)
│ └── meteor-client-side#1.2.1 incompatible with ~0.2.2 (0.2.3 available, latest is 1.2.1)
├─┬ ionic#1.2.4
│ ├── angular#1.4.9 incompatible with 1.4.3 (1.4.3 available, latest is 1.5.0-rc.2)
│ ├─┬ angular-animate#1.4.3 (latest is 1.5.0-rc.2)
│ │ └── angular#1.4.9
│ ├─┬ angular-sanitize#1.4.3 (latest is 1.5.0-rc.2)
│ │ └── angular#1.4.9
│ └─┬ angular-ui-router#0.2.13 (latest is 0.2.17)
│   └── angular#1.4.9 (1.5.0-rc.2 available)
├─┬ ionic-toast#0.2.0
│ └─┬ ionic#1.2.4 (2.0.0-alpha.53 available)
│   ├── angular#1.4.9
│   ├─┬ angular-animate#1.4.3
│   │ └── angular#1.4.9
│   ├─┬ angular-sanitize#1.4.3
│   │ └── angular#1.4.9
│   └─┬ angular-ui-router#0.2.13
│     └── angular#1.4.9
├── meteor-client-side#1.2.1
```

**Comment by kokokenada** [comment]
I have replicated the problem in this repo: 

https://github.com/kokokenada/ionicToMeteorLogin

**Comment by kokokenada** [comment]
Perhaps I have a clue to where the problem is.  I am able to work around the problem temporarily, by exposing method that sets the userId. Once I call that, everything works normally.  It's a huge security problem, but at least lets me get on with the development of my app.  

Is anybody looking at this issue?  It would seem to be quite critical...

**Comment by sabativi** [comment]
I have the same issue, that i thought related to [accounts-password-client-side](https://github.com/idanwe/accounts-password-client-side/issues/3)

**Comment by kokokenada** [comment]
Yup. Looks like the same problem.  Sounds like you're stuck as I am.  The temporary work around I'm using so I can get one with my app development is:

```
Meteor.methods({
  userIDWorkAround: function (userId) {
    console.error("Unsecure work around for auth problem. Setting current user ID to: " + userId);
    this.setUserId(String(userId));
  }
});
```

An obvious and huge security hole, but it buys me some time to sort this mess out.

**Comment by sabativi** [comment]
Do you have `Meteor.userId()` also null on server ? because it is not my case, so you could simply call

```
Meteor.methods({
  userIDWorkAround: function () {
    this.setUserId(Meteor.userId());
  }
});
```

It does not work for me and i do not understand how your workaround can work...

**Comment by kokokenada** [comment]
On the client, after a successful login, pass in the userId. (Huge security hole)

```
            Meteor.call('userIDWorkAround', Meteor.userId());
```

And yes, sadly, userId is null on the server prior to the call

**Comment by sabativi** [comment]
I keep watching but have not found anything yet, the problem has been risen [here](http://stackoverflow.com/questions/35119689/how-do-call-a-meteor-server-from-an-ionic-app-and-have-it-respect-your-user-id) also

**Comment by idanwe** [comment]
@sabativi @kokokenada I guess that the problem will be solved by updating one of the bundles.

When I will have reproduce of idanwe/meteor-client-side#3 I will be able to be more accurate.

**Comment by sabativi** [comment]
Actually, while trying to replicate the problem, i found that it has nothing to do with `meteor-client-side` or any library but because of my foolishness using ES6 syntax on the server...

More precisely, i had written

```
Meteor.publish("messages", () => {
  console.log(this.userId)
})
```

which is wrong, see more details [here](http://stackoverflow.com/questions/33056884/es6-arrow-function-is-changing-the-scope-of-this-in-meteor-publish)

maybe @kokokenada this will solve your problem.

Thanks @idanwe
