### ISSUE TITLE
Ionic 2 support

### ISSUE THREAD

**Issue by ShaharLahav** [idanwe/meteor-client-side#14]
Is there a way of integrating ionic 2 with meteor-client-side ?
Thanks in advance, Shahar.

**Comment by idanwe** [comment]
you should check [angular2-meteor](https://github.com/Urigo/angular2-meteor) you can install it through npm

**Comment by ShaharLahav** [comment]
Can you explain a little further ?

**Comment by jason-c-child** [comment]
Ionic uses Angular

**Comment by ShaharLahav** [comment]
I mean, I need to bundle everything right ? With all of the dependencies ... And then what ?

**Comment by mvandenbrink** [comment]
That is what Idan (and Jason) is trying to tell you. Use the tutorial angular2-meteor, it will guide you step-by-step to integrate Angular 2 with Meteor. There is also an Ionic tutorial, but there is no tutorial for Ionic 2 with Meteor. You have to figure it out with both tutorials and combine to get it working. A few months ago I tried it with a very basic sample for an hour. But I choose to use Ionic 1 with angular-meteor 1.3 after that hour. I will give it a new try after I finished my current project.

**Comment by leizard** [comment]
@mvandenbrink, I can confirm Ionic 1 + angular-meteor 1.3.2 + meteor-client-side is a very great combination. my app has been live in 3 months and I'm happy with the result :)

**Comment by idanwe** [comment]
@leizard great to hear

**Comment by mmazloum** [comment]
for those interested in Ionic2 + Meteor there is something here : https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter, I played with it and it works fine. I'd like to connect it to another Meteor CMS to share the same Data Base with the same reactivity, any Idea on how to do that ?
