### ISSUE TITLE
Runtime config can't be overwritten

### ISSUE THREAD

**Issue by mvandenbrink** [idanwe/meteor-client-side#16]
To bypass issue #15 I used the old runtime-config style like this:

``` javascript
__meteor_runtime_config__ = {};
__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = 'https://my.server.com';
```

But this isn't working because the use of the underscore.extend function is not correct in meteor-client-side.bundle.js. I changed this to the following:

``` javascript
  __meteor_runtime_config__ = _.extend({}, {
    meteorEnv: {},
    DDP_DEFAULT_CONNECTION_URL: 'http://localhost:3000'
  }, config);
```

After this change, the override from meteor-runtime-config.js is working again.

**Comment by idanwe** [comment]
I already fixed it at https://github.com/idanwe/meteor-client-side/commit/d612c2a8f3ce1fd6e694065a4e0abdeabb912fb2

Maybe try to run `bower install` again.
If it doesn't solve your problem reopen the issue
