### ISSUE TITLE
Available on NPM

### ISSUE THREAD

**Issue by giorgiofellipe** [idanwe/meteor-client-side#17]
Why it is not available through npm?

**Comment by idanwe** [comment]
I didn't need it when I created this project.

@giorgiofellipe a PR for that will be great

**Comment by giorgiofellipe** [comment]
@idanwe unfortunately **meteor-client-side** package name was already in use

**Comment by idanwe** [comment]
@domenukk Do you want to connect this repo to yours `meteor-client-side` fork published to npm?

This repo already updated to meteor 1.3 and I think it would be better to centralize the work into one place.

@giorgiofellipe create PR for that #18 that can be change if we all agree to the "original" repo name

**Comment by domenukk** [comment]
Hey @idanwe sure, I'm happy to do whatever it takes to use your official version.

**Comment by giorgiofellipe** [comment]
@domenukk @idanwe awesome!
Idk exactly what are the steps to transfer the package, just sent new PR with the original repo name.

Hope it gets available soon.
