### ISSUE TITLE
unable to set DDP_DEFAULT_CONNECTION_URL

### ISSUE THREAD

**Issue by mixersoft** [idanwe/meteor-client-side#21]
`dist/meteor-client-side.bundle.js` is still using `_.extend()` instead of `_.defaults()` and it is overwriting my settings.

```
# around line 1388
(function() {
  var _ = Package['underscore']._;
  var config = this.__meteor_runtime_config__ || {};

  __meteor_runtime_config__ = _.extend({}, config, {
    meteorEnv: {},
    DDP_DEFAULT_CONNECTION_URL: 'http://localhost:3000'
  });
}).call(this);
```

**Comment by triasrahman** [comment]
how to set the `____meteor_runtime_config__` ? I already set the value of this variable, but still overwritten by this function. Need help.

Thanks!
