### ISSUE TITLE
Uncaught ReferenceError: Package is not defined

### ISSUE THREAD

**Issue by fellipemoraes** [idanwe/meteor-client-side#24]
I am receive this error when the app launch.

The error is in 
(anonymous function)    @   meteor-runtime-config.js:2
(anonymous function)    @   meteor-runtime-config.js:9

The line of code is var _ = Package['underscore']._;

But, the app works. This error can cause some problem in the app?

**Comment by idanwe** [comment]
@fellipemoraes can you share a repo that produce that error?
I will help me to check it further

**Comment by idanwe** [comment]
@fellipemoraes is the issue still relevant?

**Comment by idanwe** [comment]
@fellipemoraes I'm closing this for now, If it is still relevant please re open it
