### ISSUE TITLE
Underscore.Js conflict when i use Restangular and Meteor-client-side

### ISSUE THREAD

**Issue by vinaykevadia** [idanwe/meteor-client-side#26]
```
Meteor = Package.meteor.Meteor;  
global = Package.meteor.global;  
meteorEnv = Package.meteor.meteorEnv;  
//_ = Package.underscore._;  
DDP = Package['ddp-client'].DDP;  
Mongo = Package.mongo.Mongo;  
Tracker = Package.tracker.Tracker;  
Deps = Package.tracker.Deps;
```

When i added Meteor-client-side in my test project Restangular stopped working. once i commented line "_ = Package.underscore._" (line no : 23221) , Restangular is working fine now, it seems they have conflict with "_" (UnderscoreJS)

**Comment by vinaykevadia** [comment]
@idanwe i see we can build it with any packages we want, is it necessary to include Underscore Js package,  is it dependancy for meteor core packages?

**Comment by idanwe** [comment]
Yes underscore is a dependency of multiple of the meteor core projects https://atmospherejs.com/meteor/underscore
