### ISSUE TITLE
Setting __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL

### ISSUE THREAD

**Issue by mmazloum** [idanwe/meteor-client-side#28]
What exactly are the best way to set DDP_DEFAULT_CONNECTION_URL ?

I've seen i could set it in a settings.json file when in a meteor project.

In another angular2 project i tryed to set it in the root app component constructor, but i'm not sure of what it does because I still have connection errors "sometimes" while the app seems to work.

Do you have recommandation on how and where to set this ? one must be sure that the client-side meteor part is not started i guess ?

However thanks a lot for this very usefull package ;-)

**Comment by mmazloum** [comment]
For now I set the url directly inside source files and it seems to work, but I'd like to find a cleaner way

**Comment by idanwe** [comment]
@triasrahman @mmazloum I don't fully understand the problem you are facing with.

Did you try to load a script (before loading the `meteor-client-side` package) that defines:

``` javascript
__meteor_runtime_config__ = {
  DDP_DEFAULT_CONNECTION_URL: 'http://localhost:3000'
}
```

?

**Comment by ksendra** [comment]
Hi, for me this script works only on angular1/ionic1/meteor apps. We are now trying to use the same method (adding DDP_DEFAULT_CONNECTION_URL in index.html before anything else loads) - but the system tries to go for localhost:3000 regardless. Any ideas on how to fix this?

**Comment by mmazloum** [comment]
There is a not clean way :
search for localhost:3000 inside meteor-client-side node module and replace
it with your url

2016-09-23 10:39 GMT+02:00 ntoka notifications@github.com:

**Comment by ksendra** [comment]
We're building an ionic app and want to use ionic view to avoid building it all the time. Ionic view install packages on the cloud, meaning that default connection url will be used. Is there another place where we could set it?

**Comment by sosnet** [comment]
Hey, I also want to use meteor in an Ionic2 project.
But unluckily it's not working. I'm using the clone of the meteor tutorial but in the browser console I get a 404 error for each database request. It's using the wrong port, but in the meteor-runtime-config.js the correct port is set (the default one). Why is it not using the default url, but the port of ionic instead?

See more details here: http://stackoverflow.com/questions/40742303/ionic2-with-meteor

**Comment by idanwe** [comment]
There was a problem with the minified version.

The meteor-runtime-config.js need to be wrap with a self executing function to enforce that the context will be the window.

I released v1.3.5 with the fix

**Comment by idanwe** [comment]
@mmazloum @ntoka @sosnet hope everything works now

**Comment by mmazloum** [comment]
great ! I'm releasing an app right (with a dirty work arround ;-)) now but promise I'll try this soon, thanks a lot.

**Comment by sosnet** [comment]
For me it's working now without an extra config file. Thanks @idanwe!
