### ISSUE TITLE
Rollup.js Ionic 2 rc.0 base ?

### ISSUE THREAD

**Issue by mmazloum** [idanwe/meteor-client-side#31]
Are you planning to update the whatsapp tuto to work with the latest version of ionic 2-rc which is based on rollup instead of webpack ?

I've tried to follow your steps on a ionic2-rc base, but i hit this error : 
[11:17:19]  bundle dev failed:  Could not resolve 'meteor/mongo' from /Users/marwanmazloum/Desktop/Developpement/XX/api/server/daySchedule.ts

[11:17:19]  Error: Could not resolve 'meteor/mongo' from /Users/marwanmazloum/Desktop/Developpement/XX/api/server/daySchedule.ts
    at Error (native)
    at /Users/marwanmazloum/Desktop/Developpement/XX/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/marwanmazloum/Desktop/Developpement/XX/node_modules/browser-resolve/index.js:265:24
    at /Users/marwanmazloum/Desktop/Developpement/XX/node_modules/resolve/lib/async.js:46:14
    at process (/Users/marwanmazloum/Desktop/Developpement/XX/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/marwanmazloum/Desktop/Developpement/XX/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/marwanmazloum/Desktop/Developpement/XX/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/marwanmazloum/Desktop/Developpement/XX/node_modules/resolve/lib/async.js:92:31)
    at /Users/marwanmazloum/Desktop/Developpement/XX/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

any idea ?

**Comment by idanwe** [comment]
It's not in my planning.

I now that @dotansimha tried to use this project with ionic2 and rollup and as far as I know he decided to wait for ionic release with Webpack.

**Comment by mmazloum** [comment]
@idanwe yes I understand, I should have closed this issue.

**Comment by dotansimha** [comment]
@mmazloum I had the same issue with rc0 since Ionic removed Webpack support and added Rollup instead, which uses es2016 modules and not regular CommonJS. 
In rc1 they added the option to work with Webpack (https://forum.ionicframework.com/t/help-us-test-webpack-support-in-ionic-2-app-scripts/67507/).
In a few days, we will update the whatsapp clone tutorial with Meteor & Ionic CLI.

**Comment by mmazloum** [comment]
@dotansimha Yes I've seen 'the repo' googling arround ;-) I had tried on my side to upgrade with webpack after the ionic app script beta release but I'm not good enough in those bundeling stuff.

When you release the new tuto, i'll have time too play with it if you want a feedback on it.

Thanks the team for your usefull work.

**Comment by dotansimha** [comment]
@mmazloum I just done with creating the tutorial's commits, it's in: https://github.com/DAB0mB/ionic2-meteor-messenger/tree/step-by-step-new

In the next few days I will update the actual tutorial text and update the tutorial on angular-meteor.com

**Comment by ekhmoi** [comment]
Has anybody successfully started the latest version from this link? : https://github.com/DAB0mB/ionic2-meteor-messenger/tree/step-by-step-new

it gives me plenty of errors

**Comment by dotansimha** [comment]
@ekhmoi what version of Ionic and Cordova do you have installed globally? make sure to install the latest:

```
$ npm install ionic cordova
```

Also, what errors do you see?

**Comment by ekhmoi** [comment]
@dotansimha ,
here is what i did.
1. install latest node js
2. npm install ionic cordova -g
3. clone the repository
4. run npm install inside root folder of the project
   -Gave an error: "UNMET PEER DEPENDENCY meteor-client-side@1.3.4"
5. ignore the error and run npm install inside ./api folder
   -Gave an error: "UNMET PEER DEPENDENCY rxjs@^5.0.0-beta.12"
6. ignore the errors and run meteor/ionic serve (check the outputs below)
[meteor.output.txt](https://github.com/idanwe/meteor-client-side/files/571271/meteor.output.txt)
[ionic.output.txt](https://github.com/idanwe/meteor-client-side/files/571261/ionic.output.txt)

`ionic info` result

---

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.

6.4.0

Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.38
OS: Windows 7 SP1
Node Version: v6.9.1

**Comment by dotansimha** [comment]
Do you use the correct branch after cloning it? 
Also, the `UNMET PEER DEPENDENCY` should be a warning, not an error, if you are using latest version of Node.
You Meteor output looks fine, your Ionic output have some issue because you did not run `npm install` in the root directory...

**Comment by ekhmoi** [comment]
I cloned the step-by-step-new branch
also tried with downloading directly zip
there is no way that i didnt run `npm install` in the root directory :)
Check the below file to see root directory and npm install output
[ionic.npm.install.txt](https://github.com/idanwe/meteor-client-side/files/571330/ionic.npm.install.txt)

**Comment by ekhmoi** [comment]
here is the all steps from terminal output 
[ionic.error.txt](https://github.com/idanwe/meteor-client-side/files/572000/ionic.error.txt)

**Comment by ekhmoi** [comment]
_Update_
i had to run `npm install meteor-typings` seperately inside ionic root folder too

**Comment by dotansimha** [comment]
@ekhmoi yeah that's what I meant, and I will add meteor-typings if it's missing. Thanks!
