### ISSUE TITLE
Are there any documentation?

### ISSUE THREAD

**Issue by radiegtya** [idanwe/meteor-client-side#4]
I need the documentation (not just example and blog). Simple documentation like docs.meteor.com but with meteor-client-side version will be very helpful. Thanks

**Comment by idanwe** [comment]
The API is the [Meteor API](docs.meteor.com) for the [client side of the packages](https://github.com/idanwe/meteor-client-side/blob/master/bundle-min.sh#L35-L51) that are bundled here.

The only thing that you need to define is 
`__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = <SERVER_URL>`

@radiegtya Which additional documentation do you need?

**Comment by radiegtya** [comment]
this meteor client side plugin is created to make separated angular for frontend and meteor for backend. So I still don't have clear understanding about what Meteor API that can be used, and in what syntax style. 

The Documentation I need is something like this (same with docs.meteor.com but for this angular version for separated backend n frontend)

Documentation:
1. setting up:
**meteor_runtime_config**.DDP_DEFAULT_CONNECTION_URL = <SERVER_URL>
2. subscribe: 
$scope.$meteorSubscribe('blah');
3. collection
3.1. collection find
$scope.$meteorCollection.get('what');
etc2

Thanks @idanwe

**Comment by idanwe** [comment]
The project isn't created specific for angular. 
Although, the examples mentioned at the README are only with angular-meteor.
For example, I have private project that use meteor-client-side to connect chrome extension with meteor server via DDP.

Meteor as library is just bundle of js packages. meteor-client-side is just the bundle of the browser side of those packages.
This package expose as globals `Meteor`, `check`, `Tracker`, `DDP` and [few more](https://github.com/idanwe/meteor-client-side/blob/master/bundle-min.sh#L35-L51)
Therefor, the API is the original Meteor API without any changes.

If you combine it with the angular-meteor bower package you can use the complete [angular-meteor API](http://angular-meteor.com/api/meteorCollection).

**Comment by radiegtya** [comment]
Oh I see thanks for the answer, case closed
