### ISSUE TITLE
update failed: Access denied warning

### ISSUE THREAD

**Issue by leizard** [idanwe/meteor-client-side#7]
It shows the following warning every time I use $meteor.call a server method

```
update failed: Access denied. In a restricted collection you can only update documents, not replace them. Use a Mongo update operator, such as '$set'.
```

Is it an issue somewhere ?

**Comment by idanwe** [comment]
It is probably because you removed from your server the `insecure` package that allows to make mongo update from the client side

**Comment by leizard** [comment]
It solves now :)
