### ISSUE TITLE
DDP_DEFAULT_CONNECTION_URL not working on mobile client?

### ISSUE THREAD

**Issue by mvandenbrink** [idanwe/meteor-client-side#9]
I'm having an issue with the DDP connection. I started the development of a mobile app with Ionic and Meteor (server side) and this is working very well with your packages and the tutorials from Angular-Meteor. After a few days, I've an working app on my development machine. But testing on my android device didn't work well. I thought it was something with my development setup and testing in Chrome works very well, so why should spend time to it I thought. 

But today I wanted to show my mobile app, so I made a package for the Meteor server and deployed it. I've deployed the server part of the Meteor package behind an NGINX proxy. On my development machine I changed the DDP_DEFAULT_CONNECTION_URL from 'http://localhost:3000' to my own URL and yes this is working. I build again an android package and installed this on my android phone (ionic run android). The package is deployed, but still I can't make a connection (login form). In my NGINX server there is no connection from my android phone. While I'm using the same configuration from my development machine which is working. I can see NGINX log messages for a websocket connection and I can use the login form. 

When I use meteor for building an android package, I've to use --mobile-server parameter to point to the right meteor server package.

ionic version : 1.2.1
angular-meteor : 1.3.1
meteor-client-side : 1.2.0

Do you have any idea what is going wrong?

**Comment by idanwe** [comment]
The meteor --mobile-server parameter sets the ddp connection of mobile app build by meteor cli.

So, in your scenario it doesn't sound relevant.

I think that you need to make sure that the mobile app is allowed to connect to your desired server url.

**Comment by mvandenbrink** [comment]
You are right. Found an option in chrome (chrome://inspect/#devices) to debug the mobile app. I can see these log messages:

meteor-client-side.bundle.min.js:5 GET http://myserver.utl/sockjs/info?cb=g08ato6emr 404 (Not Found)

So it seems to be a DNS error or other connection error. Going to try something else. Thanks for your reponse.

**Comment by mvandenbrink** [comment]
I solved my problem this morning. I'm using a new Cordova which needs some extra security settings. You have to add the package cordova-plugin-whitelist (https://github.com/apache/cordova-plugin-whitelist).

```
ionic plugin add https://github.com/apache/cordova-plugin-whitelist.git
```

And add the following line (don't use this in production) to the config.xml

```
<allow-navigation href="*" />
```

In the index.html I had to add a Content-Security-Policy meta tag

```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">
```

Et voila, it is working now.
